baseurl = "https://koya-mamy3aku.github.io/public/"
languageCode = "ja-jp"
title = "週末のホームページ"
theme = "simple"
enableGitInfo = true
pygmentsCodeFences = true

[markup.goldmark.renderer]
  unsafe = true
